version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src
    networks:
      - distributed-network

networks:
  distributed-network:
    driver: bridge