version: '3.8'
services:
  node1:
    build: .
    image: cd_node
    network_mode: host
    environment:
      - PORT=7000

  node2:
    build: .
    image: cd_node
    network_mode: host
    environment:
      - PORT=7001

  node3:
    build: .
    image: cd_node
    network_mode: host
    environment:
      - PORT=7002